"""011_notificaciones_email_art_8_4

Revision ID: 2e7f77ee001e
Revises: 81b45384f520
Create Date: 2026-09-05 15:57:11.827036

Canal real de notificaciones al cliente por correo (Art. 8.4 de la
constitución — ya admitía "correo electrónico o similar" sin fijar
proveedor, así que elegir Gmail SMTP es una decisión de implementación,
no una enmienda) — agrega `notificacion_enviada`/
`notificacion_detalle` a `cupon` (005-promociones-inteligentes) y a
`campana_recuperacion` (002-clientes-fidelizacion), las tres alertas que
el artículo exige: cupón de cumpleaños, cupón por patrón de compra y
alerta de campaña de recuperación. `fecha_envio` en ambas tablas ya
existía pero solo marcaba cuándo se creó el registro, nunca una entrega
real — estas columnas nuevas registran el resultado real del intento de
envío (ver app/services/notificaciones.py), nunca lo asumen.
`notificacion_enviada=False` con un `notificacion_detalle` explicando por
qué es un estado válido y esperado (SMTP sin configurar, contacto del
cliente sin forma de correo, rechazo del servidor) — no un error de
integridad.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7f77ee001e'
down_revision: Union[str, None] = '81b45384f520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campana_recuperacion', sa.Column('notificacion_enviada', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('campana_recuperacion', sa.Column('notificacion_detalle', sa.Text(), nullable=True))
    op.add_column('cupon', sa.Column('notificacion_enviada', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('cupon', sa.Column('notificacion_detalle', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cupon', 'notificacion_detalle')
    op.drop_column('cupon', 'notificacion_enviada')
    op.drop_column('campana_recuperacion', 'notificacion_detalle')
    op.drop_column('campana_recuperacion', 'notificacion_enviada')
    # ### end Alembic commands ###
