"""003_precios_margenes

Revision ID: 2fc91848ff6d
Revises: c3fd49d3797d
Create Date: 2026-09-05 00:03:24.682042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc91848ff6d'
down_revision: Union[str, None] = 'c3fd49d3797d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canal_competencia',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('frecuencia_monitoreo_dias', sa.SmallInteger(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('frecuencia_monitoreo_dias > 0', name='ck_canal_frecuencia_positiva'),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('clasificacion_comercial',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('margen_objetivo_min', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('margen_objetivo_max', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('margen_objetivo_max > margen_objetivo_min', name='ck_clasif_margen_max_mayor'),
    sa.CheckConstraint('margen_objetivo_min >= 0', name='ck_clasif_margen_min_no_negativo'),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('estado_recomendacion',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('es_estado_final', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('fuente_precio',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('requiere_justificacion', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('fuente_competencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('canal_codigo', sa.String(length=40), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['canal_codigo'], ['canal_competencia.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('clasificacion_producto',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('clasificacion', sa.String(length=40), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['clasificacion'], ['clasificacion_comercial.codigo'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('producto_id')
    )
    op.create_table('precio_competencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('fuente_competencia_id', sa.Integer(), nullable=False),
    sa.Column('precio_referencia', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.CheckConstraint('precio_referencia >= 0', name='ck_precio_competencia_no_negativo'),
    sa.ForeignKeyConstraint(['fuente_competencia_id'], ['fuente_competencia.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_precio_competencia_producto_fecha', 'precio_competencia', ['producto_id', 'fecha_registro'], unique=False)
    op.create_index('ix_precio_competencia_producto_fuente_fecha', 'precio_competencia', ['producto_id', 'fuente_competencia_id', 'fecha_registro'], unique=False)
    op.create_table('producto_clasificacion_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('clasificacion', sa.String(length=40), nullable=False),
    sa.Column('fecha_desde', sa.DateTime(), nullable=False),
    sa.Column('fecha_hasta', sa.DateTime(), nullable=True),
    sa.Column('motivo_cambio', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('fecha_hasta IS NULL OR fecha_hasta > fecha_desde', name='ck_clasif_hist_rango_valido'),
    sa.CheckConstraint('length(motivo_cambio) >= 10', name='ck_clasif_hist_motivo_minimo'),
    sa.ForeignKeyConstraint(['clasificacion'], ['clasificacion_comercial.codigo'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clasif_hist_producto_fecha', 'producto_clasificacion_historial', ['producto_id', 'fecha_desde'], unique=False)
    op.create_index('ux_clasif_hist_vigente', 'producto_clasificacion_historial', ['producto_id'], unique=True, postgresql_where=sa.text('fecha_hasta IS NULL'))
    op.create_table('historial_precio_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fuente', sa.String(length=40), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.CheckConstraint('precio_venta >= 0', name='ck_historial_precio_no_negativo'),
    sa.ForeignKeyConstraint(['fuente'], ['fuente_precio.codigo'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_historial_precio_producto_sucursal_vigente', 'historial_precio_producto', ['producto_id', 'sucursal_id', 'vigente_desde'], unique=False)
    op.create_table('recomendacion_precio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('precio_actual_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_recomendado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=40), server_default='pendiente', nullable=False),
    sa.Column('fecha_generada', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('resuelto_por', sa.Integer(), nullable=True),
    sa.CheckConstraint('length(justificacion) >= 10', name='ck_recomendacion_justificacion_minima'),
    sa.CheckConstraint('precio_recomendado >= 0', name='ck_recomendacion_precio_no_negativo'),
    sa.ForeignKeyConstraint(['estado'], ['estado_recomendacion.codigo'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['resuelto_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recomendacion_sucursal_estado', 'recomendacion_precio', ['sucursal_id', 'estado'], unique=False)
    op.create_index('ux_recomendacion_pendiente_unica', 'recomendacion_precio', ['producto_id', 'sucursal_id'], unique=True, postgresql_where=sa.text("estado = 'pendiente'"))
    # ### end Alembic commands ###

    _seed()


# ---------------------------------------------------------------------------
# Seed de los 4 catálogos de 003 (enmienda §7) + recursos/permisos RBAC que
# este módulo agrega a la matriz de 010. `fuente_competencia` no lleva seed
# aquí: es id SERIAL editable por el negocio (mismo caso que `categoria`),
# se carga desde la app, no desde la migración.
# ---------------------------------------------------------------------------


def _seed() -> None:
    clasificacion_comercial = sa.table(
        "clasificacion_comercial",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("margen_objetivo_min", sa.Numeric),
        sa.column("margen_objetivo_max", sa.Numeric),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        clasificacion_comercial,
        [
            {"codigo": "gancho", "etiqueta": "Gancho", "margen_objetivo_min": 5, "margen_objetivo_max": 15, "orden": 1},
            {"codigo": "nicho", "etiqueta": "Nicho", "margen_objetivo_min": 20, "margen_objetivo_max": 45, "orden": 2},
        ],
    )

    fuente_precio = sa.table(
        "fuente_precio",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("requiere_justificacion", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        fuente_precio,
        [
            {"codigo": "manual", "etiqueta": "Manual", "requiere_justificacion": False, "orden": 1},
            {"codigo": "motor_dinamico", "etiqueta": "Motor dinámico", "requiere_justificacion": True, "orden": 2},
        ],
    )

    canal_competencia = sa.table(
        "canal_competencia",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("frecuencia_monitoreo_dias", sa.SmallInteger),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        canal_competencia,
        [
            {"codigo": "tienda_fisica", "etiqueta": "Tienda física", "frecuencia_monitoreo_dias": 7, "orden": 1},
            {"codigo": "supermercado", "etiqueta": "Supermercado", "frecuencia_monitoreo_dias": 7, "orden": 2},
            {"codigo": "canal_digital", "etiqueta": "Canal digital", "frecuencia_monitoreo_dias": 1, "orden": 3},
        ],
    )

    estado_recomendacion = sa.table(
        "estado_recomendacion",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("es_estado_final", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        estado_recomendacion,
        [
            {"codigo": "pendiente", "etiqueta": "Pendiente", "es_estado_final": False, "orden": 1},
            {"codigo": "aceptada", "etiqueta": "Aceptada", "es_estado_final": True, "orden": 2},
            {"codigo": "rechazada", "etiqueta": "Rechazada", "es_estado_final": True, "orden": 3},
            {"codigo": "obsoleta", "etiqueta": "Obsoleta", "es_estado_final": True, "orden": 4},
        ],
    )

    recurso_sistema = sa.table(
        "recurso_sistema",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("modulo", sa.String),
        sa.column("es_auditable", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        recurso_sistema,
        [
            {"codigo": "precio", "etiqueta": "Precio y clasificación comercial", "modulo": "003-precios-margenes", "es_auditable": True, "orden": 11},
            {"codigo": "recomendacion_precio", "etiqueta": "Recomendación de precio", "modulo": "003-precios-margenes", "es_auditable": True, "orden": 12},
        ],
    )

    permiso_rol = sa.table(
        "permiso_rol",
        sa.column("rol", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("permitido", sa.Boolean),
    )

    # precio (historial_precio_producto, clasificacion_producto/historial,
    # precio_competencia, fuente_competencia): política de pricing —
    # dueño y compras la administran (compras negocia con proveedores y
    # fija el precio base); sucursal y cajero solo consultan.
    # recomendacion_precio: aceptar/rechazar una propuesta del motor
    # dinámico es decisión de negocio — dueño y compras pueden resolverla
    # (actualizar = cambiar su estado), sucursal solo la ve, cajero nada.
    matrices = {
        "dueno": {
            "precio": {"crear": True, "leer": True, "actualizar": True},
            "recomendacion_precio": {"crear": True, "leer": True, "actualizar": True},
        },
        "encargado_compras": {
            "precio": {"crear": True, "leer": True, "actualizar": True},
            "recomendacion_precio": {"crear": False, "leer": True, "actualizar": True},
        },
        "encargado_sucursal": {
            "precio": {"crear": False, "leer": True, "actualizar": False},
            "recomendacion_precio": {"crear": False, "leer": True, "actualizar": False},
        },
        "cajero": {
            "precio": {"crear": False, "leer": True, "actualizar": False},
            "recomendacion_precio": {"crear": False, "leer": False, "actualizar": False},
        },
    }

    filas = [
        {"rol": rol_codigo, "recurso": recurso, "operacion": op_codigo, "permitido": permitido}
        for rol_codigo, matriz in matrices.items()
        for recurso, ops in matriz.items()
        for op_codigo, permitido in ops.items()
    ]
    op.bulk_insert(permiso_rol, filas)


def downgrade() -> None:
    # Limpieza manual: filas de permiso_rol/recurso_sistema sembradas por
    # este módulo, en tablas de 010 que esta migración no dropea.
    op.execute("DELETE FROM permiso_rol WHERE recurso IN ('precio', 'recomendacion_precio')")
    op.execute("DELETE FROM recurso_sistema WHERE codigo IN ('precio', 'recomendacion_precio')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_recomendacion_pendiente_unica', table_name='recomendacion_precio', postgresql_where=sa.text("estado = 'pendiente'"))
    op.drop_index('ix_recomendacion_sucursal_estado', table_name='recomendacion_precio')
    op.drop_table('recomendacion_precio')
    op.drop_index('ix_historial_precio_producto_sucursal_vigente', table_name='historial_precio_producto')
    op.drop_table('historial_precio_producto')
    op.drop_index('ux_clasif_hist_vigente', table_name='producto_clasificacion_historial', postgresql_where=sa.text('fecha_hasta IS NULL'))
    op.drop_index('ix_clasif_hist_producto_fecha', table_name='producto_clasificacion_historial')
    op.drop_table('producto_clasificacion_historial')
    op.drop_index('ix_precio_competencia_producto_fuente_fecha', table_name='precio_competencia')
    op.drop_index('ix_precio_competencia_producto_fecha', table_name='precio_competencia')
    op.drop_table('precio_competencia')
    op.drop_table('clasificacion_producto')
    op.drop_table('fuente_competencia')
    op.drop_table('fuente_precio')
    op.drop_table('estado_recomendacion')
    op.drop_table('clasificacion_comercial')
    op.drop_table('canal_competencia')
    # ### end Alembic commands ###
