"""001_layout_anaquel

Layout/anaquel limitado — hueco #8/#18 del enunciado original (huecos
adicionales confirmados, sección 5 del documento de objetivos), documentado
hasta ahora como fuera de alcance explícito. Enmienda 2026-09-05, auditoría
de riesgos derivados: `anaquel` (espacio físico por sucursal, con
capacidad_maxima opcional) y `producto_ubicacion` (asignación vigente,
un producto por sucursal a la vez — RN-CVI-010 impide superar la capacidad
declarada del anaquel).

Revision ID: 38d12694f2c1
Revises: 2e7f77ee001e
Create Date: 2026-09-05 16:45:47.150804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d12694f2c1'
down_revision: Union[str, None] = '2e7f77ee001e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anaquel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacidad_maxima IS NULL OR capacidad_maxima > 0', name='ck_anaquel_capacidad_positiva'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sucursal_id', 'codigo', name='ux_anaquel_sucursal_codigo')
    )
    op.create_table('producto_ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('anaquel_id', sa.Integer(), nullable=False),
    sa.Column('asignado_por', sa.Integer(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anaquel_id'], ['anaquel.id'], ),
    sa.ForeignKeyConstraint(['asignado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'sucursal_id', name='ux_ubicacion_producto_sucursal')
    )
    # ### end Alembic commands ###
    _seed()


def _seed() -> None:
    recurso_sistema = sa.table(
        "recurso_sistema",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("modulo", sa.String),
        sa.column("es_auditable", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        recurso_sistema,
        [
            {"codigo": "anaquel", "etiqueta": "Layout/anaquel", "modulo": "001-core-ventas-inventario", "es_auditable": True, "orden": 20},
        ],
    )

    permiso_rol = sa.table(
        "permiso_rol",
        sa.column("rol", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("permitido", sa.Boolean),
    )

    # anaquel: dueño control total; encargado_sucursal administra el layout
    # de su propia sucursal en el día a día (es su responsabilidad
    # operativa real); cajero y compras solo consultan, para ubicar/reponer
    # productos, nunca reorganizan el layout ellos mismos.
    matrices = {
        "dueno": {"crear": True, "leer": True, "actualizar": True},
        "encargado_sucursal": {"crear": True, "leer": True, "actualizar": True},
        "encargado_compras": {"crear": False, "leer": True, "actualizar": False},
        "cajero": {"crear": False, "leer": True, "actualizar": False},
    }
    filas = [
        {"rol": rol_codigo, "recurso": "anaquel", "operacion": op_codigo, "permitido": permitido}
        for rol_codigo, ops in matrices.items()
        for op_codigo, permitido in ops.items()
    ]
    op.bulk_insert(permiso_rol, filas)


def downgrade() -> None:
    op.execute("DELETE FROM permiso_rol WHERE recurso = 'anaquel'")
    op.execute("DELETE FROM recurso_sistema WHERE codigo = 'anaquel'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto_ubicacion')
    op.drop_table('anaquel')
    # ### end Alembic commands ###
