"""001_core_ventas_inventario

Revision ID: 39457fa875e2
Revises: 791f2fa5c65a
Create Date: 2026-09-04 23:58:13.392597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39457fa875e2'
down_revision: Union[str, None] = '791f2fa5c65a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('categoria_padre_id', sa.Integer(), nullable=True),
    sa.Column('es_perecedero', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('categoria_padre_id <> id', name='ck_categoria_no_autopadre'),
    sa.ForeignKeyConstraint(['categoria_padre_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estado_pago',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('es_estado_final', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('estado_venta',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('cuenta_para_ingresos', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('metodo_pago',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('es_electronico', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('unidad_medida',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('permite_decimales', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('codigo_barras', sa.Text(), nullable=True),
    sa.Column('unidad_venta_codigo', sa.String(length=20), nullable=False),
    sa.Column('unidad_inventario_codigo', sa.String(length=20), nullable=False),
    sa.Column('es_fraccionable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('factor_conversion', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('es_perecedero', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('es_fraccionable = false OR factor_conversion IS NOT NULL', name='ck_producto_fraccionable_requiere_factor'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['unidad_inventario_codigo'], ['unidad_medida.codigo'], ),
    sa.ForeignKeyConstraint(['unidad_venta_codigo'], ['unidad_medida.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras')
    )
    op.create_index('ix_producto_categoria', 'producto', ['categoria_id'], unique=False)
    op.create_table('producto_sustituto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('producto_sustituto_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('producto_sustituto_id <> producto_id', name='ck_sustituto_no_autoreferencia'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['producto_sustituto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'producto_sustituto_id', name='ux_producto_sustituto')
    )
    op.create_table('ajuste_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_ajuste', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(motivo) >= 3', name='ck_ajuste_motivo_minimo'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('fecha_caducidad', sa.Date(), nullable=False),
    sa.Column('cantidad_lote', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('cantidad_restante', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('retirado_en', sa.DateTime(), nullable=True),
    sa.Column('motivo_retiro', sa.Text(), nullable=True),
    sa.CheckConstraint('cantidad_lote > 0', name='ck_lote_cantidad_positiva'),
    sa.CheckConstraint('cantidad_restante >= 0 AND cantidad_restante <= cantidad_lote', name='ck_lote_restante_en_rango'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_disponible', sa.Numeric(precision=10, scale=3), server_default='0', nullable=False),
    sa.Column('dias_sin_venta', sa.Integer(), server_default='0', nullable=False),
    sa.Column('marcado_sin_rotacion', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=3), server_default='0', nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad_disponible >= 0', name='ck_stock_cantidad_no_negativa'),
    sa.CheckConstraint('stock_minimo >= 0', name='ck_stock_minimo_no_negativo'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'sucursal_id', name='ux_stock_producto_sucursal')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_documento', sa.Text(), sa.Computed("'V-' || lpad(id::text, 8, '0')", persisted=True), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('turno_caja_id', sa.Integer(), nullable=False),
    sa.Column('cajero_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('hora_inicio_cobro', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento_aplicado', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('iva', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=20), nullable=False),
    sa.Column('estado_pago', sa.String(length=20), server_default='pendiente', nullable=False),
    sa.Column('estado_venta', sa.String(length=20), server_default='completada', nullable=False),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('anulada_en', sa.DateTime(), nullable=True),
    sa.CheckConstraint("estado_venta <> 'anulada' OR motivo_anulacion IS NOT NULL", name='ck_venta_anulada_requiere_motivo'),
    sa.CheckConstraint('subtotal >= 0', name='ck_venta_subtotal_no_negativo'),
    sa.CheckConstraint('total = subtotal - descuento_aplicado + iva', name='ck_venta_total_coherente'),
    sa.ForeignKeyConstraint(['cajero_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['estado_pago'], ['estado_pago.codigo'], ),
    sa.ForeignKeyConstraint(['estado_venta'], ['estado_venta.codigo'], ),
    sa.ForeignKeyConstraint(['metodo_pago'], ['metodo_pago.codigo'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento')
    )
    op.create_index('ix_venta_sucursal_fecha', 'venta', ['sucursal_id', 'fecha_hora'], unique=False)
    op.create_index('ix_venta_turno_caja', 'venta', ['turno_caja_id'], unique=False)
    op.create_table('detalle_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_venta', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidad_venta_codigo', sa.String(length=20), nullable=False),
    sa.Column('cantidad_inventario', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('precio_unitario_aplicado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('cantidad_venta > 0', name='ck_detalle_cantidad_positiva'),
    sa.CheckConstraint('subtotal_item = cantidad_venta * precio_unitario_aplicado', name='ck_detalle_subtotal_coherente'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['unidad_venta_codigo'], ['unidad_medida.codigo'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    _seed()


# ---------------------------------------------------------------------------
# Seed de los 5 catálogos de 001 (enmienda §7: el seed viaja en la misma
# migración que crea la tabla) + los recursos/permisos RBAC que este módulo
# agrega a la matriz de 010 — mismo patrón que la migración anterior:
# cada módulo nuevo añade sus propios recursos y filas de permiso_rol.
# ---------------------------------------------------------------------------


def _seed() -> None:
    categoria = sa.table(
        "categoria",
        sa.column("nombre", sa.String),
        sa.column("es_perecedero", sa.Boolean),
    )
    op.bulk_insert(
        categoria,
        [
            {"nombre": "Bebidas", "es_perecedero": False},
            {"nombre": "Snacks", "es_perecedero": False},
            {"nombre": "Lácteos", "es_perecedero": True},
            {"nombre": "Abarrotes", "es_perecedero": False},
            {"nombre": "Limpieza", "es_perecedero": False},
            {"nombre": "Cuidado Personal", "es_perecedero": False},
            {"nombre": "Panadería", "es_perecedero": True},
            {"nombre": "Congelados", "es_perecedero": True},
        ],
    )

    unidad_medida = sa.table(
        "unidad_medida",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("permite_decimales", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        unidad_medida,
        [
            {"codigo": "unidad", "etiqueta": "Unidad", "permite_decimales": False, "orden": 1},
            {"codigo": "libra", "etiqueta": "Libra", "permite_decimales": True, "orden": 2},
            {"codigo": "kilo", "etiqueta": "Kilogramo", "permite_decimales": True, "orden": 3},
            {"codigo": "litro", "etiqueta": "Litro", "permite_decimales": True, "orden": 4},
            {"codigo": "funda", "etiqueta": "Funda", "permite_decimales": False, "orden": 5},
            {"codigo": "caja", "etiqueta": "Caja", "permite_decimales": False, "orden": 6},
        ],
    )

    metodo_pago = sa.table(
        "metodo_pago",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("es_electronico", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        metodo_pago,
        [
            {"codigo": "efectivo", "etiqueta": "Efectivo", "es_electronico": False, "orden": 1},
            {"codigo": "tarjeta", "etiqueta": "Tarjeta", "es_electronico": True, "orden": 2},
            {"codigo": "electronico", "etiqueta": "Pago electrónico", "es_electronico": True, "orden": 3},
        ],
    )

    estado_pago = sa.table(
        "estado_pago",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("es_estado_final", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        estado_pago,
        [
            {"codigo": "pendiente", "etiqueta": "Pendiente", "es_estado_final": False, "orden": 1},
            {"codigo": "aprobado", "etiqueta": "Aprobado", "es_estado_final": True, "orden": 2},
            {"codigo": "rechazado", "etiqueta": "Rechazado", "es_estado_final": True, "orden": 3},
        ],
    )

    estado_venta = sa.table(
        "estado_venta",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("cuenta_para_ingresos", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        estado_venta,
        [
            {"codigo": "completada", "etiqueta": "Completada", "cuenta_para_ingresos": True, "orden": 1},
            {"codigo": "anulada", "etiqueta": "Anulada", "cuenta_para_ingresos": False, "orden": 2},
        ],
    )

    # -- RBAC: nuevos recursos de 001 sobre la matriz sembrada en 010 --------
    recurso_sistema = sa.table(
        "recurso_sistema",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("modulo", sa.String),
        sa.column("es_auditable", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        recurso_sistema,
        [
            {"codigo": "producto", "etiqueta": "Producto", "modulo": "001-core-ventas-inventario", "es_auditable": True, "orden": 6},
            {"codigo": "inventario", "etiqueta": "Inventario", "modulo": "001-core-ventas-inventario", "es_auditable": True, "orden": 7},
            {"codigo": "venta", "etiqueta": "Venta", "modulo": "001-core-ventas-inventario", "es_auditable": True, "orden": 8},
        ],
    )

    permiso_rol = sa.table(
        "permiso_rol",
        sa.column("rol", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("permitido", sa.Boolean),
    )

    # producto: dueño y encargado_compras administran el catálogo completo
    # (compras es quien negocia con proveedores qué se vende); sucursal y
    # cajero solo lo consultan.
    # inventario (stock/lotes/ajustes): dueño con control total; compras
    # solo lectura (le interesa qué se agota, no ajusta stock); sucursal
    # ajusta el suyo (mermas, recuentos); cajero solo lectura.
    # venta: dueño con control total (incluida anulación); compras y
    # cajero según su función — el cajero registra pero no anula, la
    # anulación exige un rol con más jerarquía (separación de funciones,
    # tema central de 006-caja-mermas-fraude).
    matrices = {
        "dueno": {
            "producto": {"crear": True, "leer": True, "actualizar": True},
            "inventario": {"crear": True, "leer": True, "actualizar": True},
            "venta": {"crear": True, "leer": True, "actualizar": True},
        },
        "encargado_compras": {
            "producto": {"crear": True, "leer": True, "actualizar": True},
            "inventario": {"crear": False, "leer": True, "actualizar": False},
            "venta": {"crear": False, "leer": True, "actualizar": False},
        },
        "encargado_sucursal": {
            "producto": {"crear": False, "leer": True, "actualizar": False},
            "inventario": {"crear": True, "leer": True, "actualizar": True},
            "venta": {"crear": False, "leer": True, "actualizar": True},
        },
        "cajero": {
            "producto": {"crear": False, "leer": True, "actualizar": False},
            "inventario": {"crear": False, "leer": True, "actualizar": False},
            "venta": {"crear": True, "leer": True, "actualizar": False},
        },
    }

    filas = [
        {"rol": rol_codigo, "recurso": recurso, "operacion": op_codigo, "permitido": permitido}
        for rol_codigo, matriz in matrices.items()
        for recurso, ops in matriz.items()
        for op_codigo, permitido in ops.items()
    ]
    op.bulk_insert(permiso_rol, filas)


def downgrade() -> None:
    # Limpieza manual: las filas de permiso_rol/recurso_sistema sembradas por
    # este módulo viven en tablas de 010 que esta migración no crea ni dropea.
    op.execute(
        "DELETE FROM permiso_rol WHERE recurso IN ('producto', 'inventario', 'venta')"
    )
    op.execute(
        "DELETE FROM recurso_sistema WHERE codigo IN ('producto', 'inventario', 'venta')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_venta')
    op.drop_index('ix_venta_turno_caja', table_name='venta')
    op.drop_index('ix_venta_sucursal_fecha', table_name='venta')
    op.drop_table('venta')
    op.drop_table('stock_sucursal')
    op.drop_table('lote_producto')
    op.drop_table('ajuste_inventario')
    op.drop_table('producto_sustituto')
    op.drop_index('ix_producto_categoria', table_name='producto')
    op.drop_table('producto')
    op.drop_table('unidad_medida')
    op.drop_table('metodo_pago')
    op.drop_table('estado_venta')
    op.drop_table('estado_pago')
    op.drop_table('categoria')
    # ### end Alembic commands ###
