"""004_pronostico_demanda

Revision ID: 72527eac255c
Revises: 2fc91848ff6d
Create Date: 2026-09-05 00:05:50.589467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72527eac255c'
down_revision: Union[str, None] = '2fc91848ff6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_evento_local',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('afecta_demanda_al_alza', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('demanda_insatisfecha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cajero_id', sa.Integer(), nullable=False),
    sa.Column('hora_evento', sa.DateTime(), nullable=False),
    sa.Column('hora_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sustituto_ofrecido_id', sa.Integer(), nullable=True),
    sa.Column('sustituto_aceptado', sa.Boolean(), nullable=True),
    sa.CheckConstraint('sustituto_aceptado IS NULL OR sustituto_ofrecido_id IS NOT NULL', name='ck_demanda_insatisfecha_sustituto_coherente'),
    sa.ForeignKeyConstraint(['cajero_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['sustituto_ofrecido_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_demanda_insatisfecha_sucursal_producto_hora', 'demanda_insatisfecha', ['sucursal_id', 'producto_id', 'hora_evento'], unique=False)
    op.create_table('evento_local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fecha_fin >= fecha_inicio', name='ck_evento_local_rango_valido'),
    sa.CheckConstraint('length(descripcion) >= 3', name='ck_evento_local_descripcion_minima'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['tipo'], ['tipo_evento_local.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evento_local_fechas', 'evento_local', ['fecha_inicio', 'fecha_fin'], unique=False)
    op.create_index('ix_evento_local_sucursal_fecha', 'evento_local', ['sucursal_id', 'fecha_inicio'], unique=False)
    op.create_table('pronostico_demanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_recomendada', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('tamano_muestra', sa.Integer(), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fin', sa.Date(), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad_recomendada >= 0', name='ck_pronostico_cantidad_no_negativa'),
    sa.CheckConstraint('tamano_muestra > 0', name='ck_pronostico_muestra_positiva'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pronostico_producto_sucursal_fecha', 'pronostico_demanda', ['producto_id', 'sucursal_id', 'fecha_calculo'], unique=False)
    # ### end Alembic commands ###

    _seed()


# ---------------------------------------------------------------------------
# Seed del catálogo de 004 (enmienda §7) + recursos/permisos RBAC.
# ---------------------------------------------------------------------------


def _seed() -> None:
    tipo_evento_local = sa.table(
        "tipo_evento_local",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("afecta_demanda_al_alza", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        tipo_evento_local,
        [
            {"codigo": "feriado", "etiqueta": "Feriado", "afecta_demanda_al_alza": True, "orden": 1},
            {"codigo": "fiesta_patronal", "etiqueta": "Fiesta patronal", "afecta_demanda_al_alza": True, "orden": 2},
            {"codigo": "evento_comunitario", "etiqueta": "Evento comunitario", "afecta_demanda_al_alza": True, "orden": 3},
            {"codigo": "clima_extremo", "etiqueta": "Clima extremo", "afecta_demanda_al_alza": False, "orden": 4},
            {"codigo": "corte_servicios", "etiqueta": "Corte de servicios", "afecta_demanda_al_alza": False, "orden": 5},
        ],
    )

    recurso_sistema = sa.table(
        "recurso_sistema",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("modulo", sa.String),
        sa.column("es_auditable", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        recurso_sistema,
        [
            {"codigo": "demanda", "etiqueta": "Demanda insatisfecha y pronóstico", "modulo": "004-pronostico-demanda", "es_auditable": True, "orden": 13},
            {"codigo": "evento_local", "etiqueta": "Evento local", "modulo": "004-pronostico-demanda", "es_auditable": True, "orden": 14},
        ],
    )

    permiso_rol = sa.table(
        "permiso_rol",
        sa.column("rol", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("permitido", sa.Boolean),
    )

    # demanda (demanda_insatisfecha + pronostico_demanda, ambas append-only
    # — sin "actualizar" real en ningún rol): el cajero es quien la
    # registra en el POS ante un quiebre de stock; sucursal también puede;
    # compras solo la consulta para decidir reposición; dueño solo lectura.
    # evento_local: registrado normalmente por quien opera la sucursal;
    # dueño puede editarlo (no es append-only estricto, ver docstring).
    matrices = {
        "dueno": {
            "demanda": {"crear": False, "leer": True, "actualizar": False},
            "evento_local": {"crear": True, "leer": True, "actualizar": True},
        },
        "encargado_compras": {
            "demanda": {"crear": False, "leer": True, "actualizar": False},
            "evento_local": {"crear": False, "leer": True, "actualizar": False},
        },
        "encargado_sucursal": {
            "demanda": {"crear": True, "leer": True, "actualizar": False},
            "evento_local": {"crear": True, "leer": True, "actualizar": True},
        },
        "cajero": {
            "demanda": {"crear": True, "leer": True, "actualizar": False},
            "evento_local": {"crear": False, "leer": True, "actualizar": False},
        },
    }

    filas = [
        {"rol": rol_codigo, "recurso": recurso, "operacion": op_codigo, "permitido": permitido}
        for rol_codigo, matriz in matrices.items()
        for recurso, ops in matriz.items()
        for op_codigo, permitido in ops.items()
    ]
    op.bulk_insert(permiso_rol, filas)


def downgrade() -> None:
    op.execute("DELETE FROM permiso_rol WHERE recurso IN ('demanda', 'evento_local')")
    op.execute("DELETE FROM recurso_sistema WHERE codigo IN ('demanda', 'evento_local')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pronostico_producto_sucursal_fecha', table_name='pronostico_demanda')
    op.drop_table('pronostico_demanda')
    op.drop_index('ix_evento_local_sucursal_fecha', table_name='evento_local')
    op.drop_index('ix_evento_local_fechas', table_name='evento_local')
    op.drop_table('evento_local')
    op.drop_index('ix_demanda_insatisfecha_sucursal_producto_hora', table_name='demanda_insatisfecha')
    op.drop_table('demanda_insatisfecha')
    op.drop_table('tipo_evento_local')
    # ### end Alembic commands ###
