"""010 administracion y 009 expansion: catalogos maestros y tablas base

Revision ID: 791f2fa5c65a
Revises: 
Create Date: 2026-09-04 23:03:39.628962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '791f2fa5c65a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_solicitud_arco',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('es_estado_final', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('estado_sucursal',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('opera_ventas', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('item_checklist_apertura',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=120), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('es_bloqueante', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('operacion',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('es_escritura', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('recurso_sistema',
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('etiqueta', sa.String(length=120), nullable=False),
    sa.Column('modulo', sa.String(length=60), nullable=False),
    sa.Column('es_auditable', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('rol',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('nivel_jerarquico', sa.SmallInteger(), nullable=False),
    sa.Column('alcance_cadena', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('nivel_jerarquico BETWEEN 1 AND 99', name='ck_rol_nivel_jerarquico_rango'),
    sa.PrimaryKeyConstraint('codigo'),
    sa.UniqueConstraint('nivel_jerarquico')
    )
    op.create_table('tipo_solicitud_arco',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('plazo_respuesta_dias', sa.SmallInteger(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('plazo_respuesta_dias > 0', name='ck_tipo_arco_plazo_positivo'),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('permiso_rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=40), nullable=False),
    sa.Column('recurso', sa.String(length=60), nullable=False),
    sa.Column('operacion', sa.String(length=40), nullable=False),
    sa.Column('permitido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['operacion'], ['operacion.codigo'], ),
    sa.ForeignKeyConstraint(['recurso'], ['recurso_sistema.codigo'], ),
    sa.ForeignKeyConstraint(['rol'], ['rol.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol', 'recurso', 'operacion', name='ux_permiso_rol_recurso_operacion')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('rol', sa.String(length=40), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rol'], ['rol.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('historial_parametro_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.Text(), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_historial_parametro_clave_vigente', 'historial_parametro_sistema', ['clave', 'vigente_desde'], unique=False)
    op.create_table('solicitud_arco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=40), server_default='pendiente', nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('atendida_por', sa.Integer(), nullable=True),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.CheckConstraint("estado = 'pendiente' OR (fecha_resolucion IS NOT NULL AND atendida_por IS NOT NULL)", name='ck_solicitud_arco_resuelta_completa'),
    sa.ForeignKeyConstraint(['atendida_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['estado'], ['estado_solicitud_arco.codigo'], ),
    sa.ForeignKeyConstraint(['tipo'], ['tipo_solicitud_arco.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=40), server_default='en_apertura', nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_activacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estado'], ['estado_sucursal.codigo'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_apertura_sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=40), nullable=False),
    sa.Column('completado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('fecha_completado', sa.DateTime(), nullable=True),
    sa.Column('completado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['completado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['item'], ['item_checklist_apertura.codigo'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sucursal_id', 'item', name='ux_checklist_sucursal_item')
    )
    op.create_table('herencia_catalogo_sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('cantidad_productos_heredados', sa.Integer(), nullable=False),
    sa.Column('cantidad_productos_pendientes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sucursal_id')
    )
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.Text(), nullable=False),
    sa.Column('recurso', sa.String(length=60), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('ip_origen', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recurso'], ['recurso_sistema.codigo'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_auditoria_exitoso_creado', 'log_auditoria', ['exitoso', 'creado_en'], unique=False)
    op.create_index('ix_log_auditoria_sucursal_creado', 'log_auditoria', ['sucursal_id', 'creado_en'], unique=False)
    op.create_index('ix_log_auditoria_usuario_creado', 'log_auditoria', ['usuario_id', 'creado_en'], unique=False)
    op.create_table('usuario_sucursal',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('asignado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'sucursal_id')
    )
    # ### end Alembic commands ###

    _seed()


# ---------------------------------------------------------------------------
# Seed de los 7 catálogos de esta migración (enmienda §7: "el seed es parte
# de la migración, no un script aparte" — un catálogo vacío rompe la FK de
# la tabla que lo usa y deja el sistema sin arrancar).
#
# `permiso_rol` cubre los 5 recursos que existen hasta esta migración
# (usuario, sucursal, checklist_apertura, parametro_sistema, solicitud_arco).
# Cada módulo nuevo (001-008, 011) agrega sus propios recursos y las filas
# de `permiso_rol` correspondientes en su propia migración — no se sembró
# de una sola vez para los 11 módulos porque la mayoría todavía no existe.
# ---------------------------------------------------------------------------


def _seed() -> None:
    rol = sa.table(
        "rol",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("nivel_jerarquico", sa.SmallInteger),
        sa.column("alcance_cadena", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        rol,
        [
            {"codigo": "dueno", "etiqueta": "Dueño", "nivel_jerarquico": 1, "alcance_cadena": True, "orden": 1},
            {"codigo": "encargado_compras", "etiqueta": "Encargado de Compras", "nivel_jerarquico": 2, "alcance_cadena": True, "orden": 2},
            {"codigo": "encargado_sucursal", "etiqueta": "Encargado de Sucursal", "nivel_jerarquico": 3, "alcance_cadena": False, "orden": 3},
            {"codigo": "cajero", "etiqueta": "Cajero", "nivel_jerarquico": 4, "alcance_cadena": False, "orden": 4},
        ],
    )

    recurso_sistema = sa.table(
        "recurso_sistema",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("modulo", sa.String),
        sa.column("es_auditable", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        recurso_sistema,
        [
            {"codigo": "usuario", "etiqueta": "Usuario", "modulo": "010-administracion", "es_auditable": True, "orden": 1},
            {"codigo": "parametro_sistema", "etiqueta": "Parámetro del sistema", "modulo": "010-administracion", "es_auditable": True, "orden": 2},
            {"codigo": "solicitud_arco", "etiqueta": "Solicitud ARCO", "modulo": "010-administracion", "es_auditable": True, "orden": 3},
            {"codigo": "sucursal", "etiqueta": "Sucursal", "modulo": "009-expansion-sucursales", "es_auditable": True, "orden": 4},
            {"codigo": "checklist_apertura", "etiqueta": "Checklist de apertura", "modulo": "009-expansion-sucursales", "es_auditable": True, "orden": 5},
        ],
    )

    operacion = sa.table(
        "operacion",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("es_escritura", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        operacion,
        [
            {"codigo": "crear", "etiqueta": "Crear", "es_escritura": True, "orden": 1},
            {"codigo": "leer", "etiqueta": "Leer", "es_escritura": False, "orden": 2},
            {"codigo": "actualizar", "etiqueta": "Actualizar", "es_escritura": True, "orden": 3},
        ],
    )

    tipo_solicitud_arco = sa.table(
        "tipo_solicitud_arco",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("plazo_respuesta_dias", sa.SmallInteger),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        tipo_solicitud_arco,
        [
            # plazo_respuesta_dias: valor de referencia (15 días hábiles),
            # a confirmar contra el texto vigente de la LOPDP (Ley 0, Art.
            # 10.1) antes de tratarlo como definitivo — la columna existe
            # justamente para poder corregirlo sin migración de esquema.
            {"codigo": "acceso", "etiqueta": "Acceso", "plazo_respuesta_dias": 15, "orden": 1},
            {"codigo": "rectificacion", "etiqueta": "Rectificación", "plazo_respuesta_dias": 15, "orden": 2},
            {"codigo": "cancelacion", "etiqueta": "Cancelación", "plazo_respuesta_dias": 15, "orden": 3},
            {"codigo": "oposicion", "etiqueta": "Oposición", "plazo_respuesta_dias": 15, "orden": 4},
        ],
    )

    estado_solicitud_arco = sa.table(
        "estado_solicitud_arco",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("es_estado_final", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        estado_solicitud_arco,
        [
            {"codigo": "pendiente", "etiqueta": "Pendiente", "es_estado_final": False, "orden": 1},
            {"codigo": "atendida", "etiqueta": "Atendida", "es_estado_final": True, "orden": 2},
            {"codigo": "rechazada", "etiqueta": "Rechazada", "es_estado_final": True, "orden": 3},
        ],
    )

    estado_sucursal = sa.table(
        "estado_sucursal",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("opera_ventas", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        estado_sucursal,
        [
            {"codigo": "en_apertura", "etiqueta": "En apertura", "opera_ventas": False, "orden": 1},
            {"codigo": "operativa", "etiqueta": "Operativa", "opera_ventas": True, "orden": 2},
            {"codigo": "cerrada", "etiqueta": "Cerrada", "opera_ventas": False, "orden": 3},
        ],
    )

    item_checklist_apertura = sa.table(
        "item_checklist_apertura",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("orden", sa.SmallInteger),
        sa.column("es_bloqueante", sa.Boolean),
    )
    op.bulk_insert(
        item_checklist_apertura,
        [
            {"codigo": "local_arrendado", "etiqueta": "Local arrendado", "orden": 1, "es_bloqueante": False},
            {"codigo": "mobiliario_instalado", "etiqueta": "Mobiliario instalado", "orden": 2, "es_bloqueante": False},
            {"codigo": "pos_instalado", "etiqueta": "POS instalado", "orden": 3, "es_bloqueante": False},
            {"codigo": "personal_asignado", "etiqueta": "Personal asignado", "orden": 4, "es_bloqueante": False},
            {"codigo": "catalogo_heredado", "etiqueta": "Catálogo heredado", "orden": 5, "es_bloqueante": False},
            {"codigo": "precios_heredados", "etiqueta": "Precios heredados", "orden": 6, "es_bloqueante": False},
            {"codigo": "inspeccion_seguridad", "etiqueta": "Inspección de seguridad", "orden": 7, "es_bloqueante": True},
            {"codigo": "permiso_municipal", "etiqueta": "Permiso municipal", "orden": 8, "es_bloqueante": True},
        ],
    )

    permiso_rol = sa.table(
        "permiso_rol",
        sa.column("rol", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("permitido", sa.Boolean),
    )
    recursos = ["usuario", "parametro_sistema", "solicitud_arco", "sucursal", "checklist_apertura"]
    operaciones = ["crear", "leer", "actualizar"]

    # dueno: alcance_cadena, acceso total — administra el sistema completo.
    matriz_dueno = {r: {o: True for o in operaciones} for r in recursos}

    # encargado_compras: alcance_cadena pero su función es compras/expansión
    # económica, no administración de usuarios ni resolución de ARCO.
    matriz_encargado_compras = {
        "usuario": {"crear": False, "leer": True, "actualizar": False},
        "parametro_sistema": {"crear": False, "leer": True, "actualizar": False},
        "solicitud_arco": {"crear": False, "leer": True, "actualizar": False},
        "sucursal": {"crear": False, "leer": True, "actualizar": False},
        "checklist_apertura": {"crear": False, "leer": True, "actualizar": False},
    }

    # encargado_sucursal: alcance de su propia sucursal — corre el día a día
    # de la apertura (completa el checklist, activa su sucursal).
    matriz_encargado_sucursal = {
        "usuario": {"crear": False, "leer": True, "actualizar": False},
        "parametro_sistema": {"crear": False, "leer": True, "actualizar": False},
        "solicitud_arco": {"crear": False, "leer": False, "actualizar": False},
        "sucursal": {"crear": False, "leer": True, "actualizar": True},
        "checklist_apertura": {"crear": False, "leer": True, "actualizar": True},
    }

    # cajero: el rol más acotado — solo lo que necesita para operar el POS.
    matriz_cajero = {
        "usuario": {"crear": False, "leer": False, "actualizar": False},
        "parametro_sistema": {"crear": False, "leer": True, "actualizar": False},
        "solicitud_arco": {"crear": False, "leer": False, "actualizar": False},
        "sucursal": {"crear": False, "leer": True, "actualizar": False},
        "checklist_apertura": {"crear": False, "leer": False, "actualizar": False},
    }

    matrices = {
        "dueno": matriz_dueno,
        "encargado_compras": matriz_encargado_compras,
        "encargado_sucursal": matriz_encargado_sucursal,
        "cajero": matriz_cajero,
    }

    filas = [
        {"rol": rol_codigo, "recurso": recurso, "operacion": op_codigo, "permitido": permitido}
        for rol_codigo, matriz in matrices.items()
        for recurso, ops in matriz.items()
        for op_codigo, permitido in ops.items()
    ]
    op.bulk_insert(permiso_rol, filas)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_sucursal')
    op.drop_index('ix_log_auditoria_usuario_creado', table_name='log_auditoria')
    op.drop_index('ix_log_auditoria_sucursal_creado', table_name='log_auditoria')
    op.drop_index('ix_log_auditoria_exitoso_creado', table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_table('herencia_catalogo_sucursal')
    op.drop_table('checklist_apertura_sucursal')
    op.drop_table('sucursal')
    op.drop_table('solicitud_arco')
    op.drop_index('ix_historial_parametro_clave_vigente', table_name='historial_parametro_sistema')
    op.drop_table('historial_parametro_sistema')
    op.drop_table('usuario')
    op.drop_table('permiso_rol')
    op.drop_table('tipo_solicitud_arco')
    op.drop_table('rol')
    op.drop_table('recurso_sistema')
    op.drop_table('operacion')
    op.drop_table('item_checklist_apertura')
    op.drop_table('estado_sucursal')
    op.drop_table('estado_solicitud_arco')
    # ### end Alembic commands ###
