"""005_promociones_inteligentes

Revision ID: 82c345f5dec1
Revises: 72527eac255c
Create Date: 2026-09-05 00:06:53.865497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c345f5dec1'
down_revision: Union[str, None] = '72527eac255c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_cupon',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('es_estado_final', sa.Boolean(), nullable=False),
    sa.Column('permite_canje', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('tipo_descuento',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('valor_maximo_permitido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('valor_maximo_permitido > 0', name='ck_tipo_descuento_maximo_positivo'),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('tipo_origen_cupon',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('es_automatico', sa.Boolean(), nullable=False),
    sa.Column('requiere_evaluacion_churn', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('cupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_origen', sa.String(length=40), nullable=False),
    sa.Column('evaluacion_churn_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('descuento_tipo', sa.String(length=40), nullable=False),
    sa.Column('descuento_valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=40), server_default='activo', nullable=False),
    sa.Column('venta_id_canje', sa.Integer(), nullable=True),
    sa.Column('fecha_canje', sa.DateTime(), nullable=True),
    sa.CheckConstraint("tipo_origen <> 'recuperacion_churn' OR evaluacion_churn_id IS NOT NULL", name='ck_cupon_churn_requiere_evaluacion'),
    sa.CheckConstraint('descuento_valor >= 0', name='ck_cupon_descuento_no_negativo'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['descuento_tipo'], ['tipo_descuento.codigo'], ),
    sa.ForeignKeyConstraint(['estado'], ['estado_cupon.codigo'], ),
    sa.ForeignKeyConstraint(['evaluacion_churn_id'], ['evaluacion_churn.id'], ),
    sa.ForeignKeyConstraint(['tipo_origen'], ['tipo_origen_cupon.codigo'], ),
    sa.ForeignKeyConstraint(['venta_id_canje'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index('ix_cupon_cliente_estado', 'cupon', ['cliente_id', 'estado'], unique=False)
    # Cierra la FK diferida de 002 (nombrada a mano — autogenerate la deja
    # sin nombre, lo que rompe el downgrade).
    op.create_foreign_key(
        "fk_campana_recuperacion_cupon", "campana_recuperacion", "cupon", ["cupon_id"], ["id"]
    )
    # ### end Alembic commands ###

    _seed()


# ---------------------------------------------------------------------------
# Seed de los 3 catálogos de 005 (enmienda §7) + recursos/permisos RBAC.
# ---------------------------------------------------------------------------


def _seed() -> None:
    tipo_origen_cupon = sa.table(
        "tipo_origen_cupon",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("es_automatico", sa.Boolean),
        sa.column("requiere_evaluacion_churn", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        tipo_origen_cupon,
        [
            {"codigo": "cumpleanos", "etiqueta": "Cumpleaños", "es_automatico": True, "requiere_evaluacion_churn": False, "orden": 1},
            {"codigo": "patron_compra", "etiqueta": "Patrón de compra", "es_automatico": True, "requiere_evaluacion_churn": False, "orden": 2},
            {"codigo": "recuperacion_churn", "etiqueta": "Recuperación de churn", "es_automatico": True, "requiere_evaluacion_churn": True, "orden": 3},
        ],
    )

    tipo_descuento = sa.table(
        "tipo_descuento",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("valor_maximo_permitido", sa.Numeric),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        tipo_descuento,
        [
            {"codigo": "porcentaje", "etiqueta": "Porcentaje", "valor_maximo_permitido": 100, "orden": 1},
            {"codigo": "monto_fijo", "etiqueta": "Monto fijo", "valor_maximo_permitido": 20, "orden": 2},
        ],
    )

    estado_cupon = sa.table(
        "estado_cupon",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("es_estado_final", sa.Boolean),
        sa.column("permite_canje", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        estado_cupon,
        [
            {"codigo": "activo", "etiqueta": "Activo", "es_estado_final": False, "permite_canje": True, "orden": 1},
            {"codigo": "canjeado", "etiqueta": "Canjeado", "es_estado_final": True, "permite_canje": False, "orden": 2},
            {"codigo": "expirado", "etiqueta": "Expirado", "es_estado_final": True, "permite_canje": False, "orden": 3},
        ],
    )

    recurso_sistema = sa.table(
        "recurso_sistema",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("modulo", sa.String),
        sa.column("es_auditable", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        recurso_sistema,
        [
            {"codigo": "cupon", "etiqueta": "Cupón", "modulo": "005-promociones-inteligentes", "es_auditable": True, "orden": 15},
        ],
    )

    permiso_rol = sa.table(
        "permiso_rol",
        sa.column("rol", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("permitido", sa.Boolean),
    )

    # cupon: dueño control total (incluye canjear/anular); sucursal y
    # cajero necesitan "actualizar" para canjear el cupón en el POS al
    # cobrar; compras solo lectura.
    matrices = {
        "dueno": {"cupon": {"crear": True, "leer": True, "actualizar": True}},
        "encargado_compras": {"cupon": {"crear": False, "leer": True, "actualizar": False}},
        "encargado_sucursal": {"cupon": {"crear": False, "leer": True, "actualizar": True}},
        "cajero": {"cupon": {"crear": False, "leer": True, "actualizar": True}},
    }

    filas = [
        {"rol": rol_codigo, "recurso": recurso, "operacion": op_codigo, "permitido": permitido}
        for rol_codigo, matriz in matrices.items()
        for recurso, ops in matriz.items()
        for op_codigo, permitido in ops.items()
    ]
    op.bulk_insert(permiso_rol, filas)


def downgrade() -> None:
    op.execute("DELETE FROM permiso_rol WHERE recurso = 'cupon'")
    op.execute("DELETE FROM recurso_sistema WHERE codigo = 'cupon'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_campana_recuperacion_cupon", "campana_recuperacion", type_="foreignkey")
    op.drop_index('ix_cupon_cliente_estado', table_name='cupon')
    op.drop_table('cupon')
    op.drop_table('tipo_origen_cupon')
    op.drop_table('tipo_descuento')
    op.drop_table('estado_cupon')
    # ### end Alembic commands ###
