"""007_pagos_seguridad

Revision ID: a17e3a247d84
Revises: d2561626e432
Create Date: 2026-09-05 00:09:52.631568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17e3a247d84'
down_revision: Union[str, None] = 'd2561626e432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_revision',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('cuenta_como_conforme', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('datafono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('codigo_serie', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_serie')
    )
    op.create_index('ix_datafono_sucursal_activo', 'datafono', ['sucursal_id', 'activo'], unique=False)
    op.create_table('revision_datafono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datafono_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revisado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['datafono_id'], ['datafono.id'], ),
    sa.ForeignKeyConstraint(['estado'], ['estado_revision.codigo'], ),
    sa.ForeignKeyConstraint(['revisado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_revision_datafono_fecha', 'revision_datafono', ['datafono_id', 'fecha_revision'], unique=False)
    # ### end Alembic commands ###

    _seed()


# ---------------------------------------------------------------------------
# Seed del catálogo de 007 (enmienda §7) + recursos/permisos RBAC.
# ---------------------------------------------------------------------------


def _seed() -> None:
    estado_revision = sa.table(
        "estado_revision",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("cuenta_como_conforme", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        estado_revision,
        [
            {"codigo": "actualizado", "etiqueta": "Actualizado", "cuenta_como_conforme": True, "orden": 1},
            {"codigo": "vencido", "etiqueta": "Vencido", "cuenta_como_conforme": False, "orden": 2},
        ],
    )

    recurso_sistema = sa.table(
        "recurso_sistema",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("modulo", sa.String),
        sa.column("es_auditable", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        recurso_sistema,
        [
            {"codigo": "datafono", "etiqueta": "Datáfono y revisiones de seguridad", "modulo": "007-pagos-seguridad", "es_auditable": True, "orden": 20},
        ],
    )

    permiso_rol = sa.table(
        "permiso_rol",
        sa.column("rol", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("permitido", sa.Boolean),
    )

    # datafono: administración de seguridad de terminales — dueño y
    # sucursal la gestionan (dan de alta, registran revisiones); compras
    # solo consulta; el cajero no tiene por qué ver ni tocar esto (RNF de
    # seguridad, no es parte de su operación diaria en el POS).
    matrices = {
        "dueno": {"datafono": {"crear": True, "leer": True, "actualizar": True}},
        "encargado_compras": {"datafono": {"crear": False, "leer": True, "actualizar": False}},
        "encargado_sucursal": {"datafono": {"crear": True, "leer": True, "actualizar": True}},
        "cajero": {"datafono": {"crear": False, "leer": False, "actualizar": False}},
    }

    filas = [
        {"rol": rol_codigo, "recurso": recurso, "operacion": op_codigo, "permitido": permitido}
        for rol_codigo, matriz in matrices.items()
        for recurso, ops in matriz.items()
        for op_codigo, permitido in ops.items()
    ]
    op.bulk_insert(permiso_rol, filas)


def downgrade() -> None:
    op.execute("DELETE FROM permiso_rol WHERE recurso = 'datafono'")
    op.execute("DELETE FROM recurso_sistema WHERE codigo = 'datafono'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_revision_datafono_fecha', table_name='revision_datafono')
    op.drop_table('revision_datafono')
    op.drop_index('ix_datafono_sucursal_activo', table_name='datafono')
    op.drop_table('datafono')
    op.drop_table('estado_revision')
    # ### end Alembic commands ###
