"""011_analitica_reportes

Revision ID: b191cc325e88
Revises: c1f8d70dba90
Create Date: 2026-09-05 00:12:03.033570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b191cc325e88'
down_revision: Union[str, None] = 'c1f8d70dba90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_ejecucion',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('es_estado_final', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('estado_version_modelo',
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('es_version_servible', sa.Boolean(), nullable=False),
    sa.Column('exige_motivo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('modelo_ml',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('algoritmo', sa.String(length=60), nullable=False),
    sa.Column('metrica_principal', sa.String(length=40), nullable=False),
    sa.Column('tamano_muestra_minimo', sa.Integer(), nullable=False),
    sa.Column('modulo_consumidor', sa.String(length=60), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('tamano_muestra_minimo > 0', name='ck_modelo_ml_muestra_minima_positiva'),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('ejecucion_pipeline_etl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dag_run_id', sa.Text(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('sucursales_procesadas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('filas_cargadas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mensaje_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['estado'], ['estado_ejecucion.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dag_run_id')
    )
    op.create_index('ix_ejecucion_etl_fecha_inicio', 'ejecucion_pipeline_etl', ['fecha_inicio'], unique=False)
    op.create_table('version_modelo_ml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=60), nullable=False),
    sa.Column('tamano_muestra', sa.Integer(), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fin', sa.Date(), nullable=False),
    sa.Column('nombre_metrica', sa.String(length=40), nullable=False),
    sa.Column('valor_metrica', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha_entrenamiento', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado != 'descartado_datos_insuficientes' OR motivo IS NOT NULL", name='ck_version_modelo_descartado_requiere_motivo'),
    sa.ForeignKeyConstraint(['estado'], ['estado_version_modelo.codigo'], ),
    sa.ForeignKeyConstraint(['modelo'], ['modelo_ml.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_version_modelo_activa', 'version_modelo_ml', ['modelo'], unique=True, postgresql_where=sa.text("estado = 'activo'"))
    op.create_table('pregunta_asistente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_texto', sa.Text(), nullable=False),
    sa.Column('consulta_generada', sa.Text(), nullable=False),
    sa.Column('respuesta_texto', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("consulta_generada != ''", name='ck_pregunta_consulta_no_vacia'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pregunta_asistente_usuario_fecha', 'pregunta_asistente', ['usuario_id', 'fecha'], unique=False)
    op.create_table('validacion_calidad_datos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejecucion_id', sa.Integer(), nullable=False),
    sa.Column('regla_validada', sa.Text(), nullable=False),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecucion_pipeline_etl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_validacion_calidad_ejecucion', 'validacion_calidad_datos', ['ejecucion_id'], unique=False)
    # Cierra la última FK diferida del proyecto (nombrada a mano).
    op.create_foreign_key(
        "fk_segmento_cliente_version_modelo",
        "segmento_cliente",
        "version_modelo_ml",
        ["version_modelo_id"],
        ["id"],
    )
    # ### end Alembic commands ###

    _seed()


# ---------------------------------------------------------------------------
# Seed de los 3 catálogos de 011 (enmienda §7) + recursos/permisos RBAC.
# Con esta migración se cierra el ciclo: los 11 módulos de specs/ existen
# y no queda ninguna FK diferida pendiente en todo el proyecto.
# ---------------------------------------------------------------------------


def _seed() -> None:
    modelo_ml = sa.table(
        "modelo_ml",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("algoritmo", sa.String),
        sa.column("metrica_principal", sa.String),
        sa.column("tamano_muestra_minimo", sa.Integer),
        sa.column("modulo_consumidor", sa.String),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        modelo_ml,
        [
            {"codigo": "demanda", "etiqueta": "Pronóstico de demanda", "algoritmo": "Regresión de series de tiempo", "metrica_principal": "MAE", "tamano_muestra_minimo": 30, "modulo_consumidor": "004-pronostico-demanda", "orden": 1},
            {"codigo": "pricing", "etiqueta": "Pricing dinámico", "algoritmo": "Regresión", "metrica_principal": "MAE", "tamano_muestra_minimo": 30, "modulo_consumidor": "003-precios-margenes", "orden": 2},
            {"codigo": "churn", "etiqueta": "Predicción de churn", "algoritmo": "Clasificación", "metrica_principal": "F1", "tamano_muestra_minimo": 30, "modulo_consumidor": "002-clientes-fidelizacion", "orden": 3},
            {"codigo": "anomalias_caja", "etiqueta": "Anomalías de cuadre de caja", "algoritmo": "Isolation Forest", "metrica_principal": "F1", "tamano_muestra_minimo": 30, "modulo_consumidor": "006-caja-mermas-fraude", "orden": 4},
            {"codigo": "segmentacion_clientes", "etiqueta": "Segmentación de clientes", "algoritmo": "K-Means", "metrica_principal": "silhouette", "tamano_muestra_minimo": 30, "modulo_consumidor": "002-clientes-fidelizacion", "orden": 5},
        ],
    )

    estado_ejecucion = sa.table(
        "estado_ejecucion",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("es_estado_final", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        estado_ejecucion,
        [
            {"codigo": "en_progreso", "etiqueta": "En progreso", "es_estado_final": False, "orden": 1},
            {"codigo": "exitoso", "etiqueta": "Exitoso", "es_estado_final": True, "orden": 2},
            {"codigo": "error", "etiqueta": "Error", "es_estado_final": True, "orden": 3},
        ],
    )

    estado_version_modelo = sa.table(
        "estado_version_modelo",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("es_version_servible", sa.Boolean),
        sa.column("exige_motivo", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        estado_version_modelo,
        [
            {"codigo": "activo", "etiqueta": "Activo", "es_version_servible": True, "exige_motivo": False, "orden": 1},
            {"codigo": "reemplazado", "etiqueta": "Reemplazado", "es_version_servible": False, "exige_motivo": False, "orden": 2},
            {"codigo": "descartado_datos_insuficientes", "etiqueta": "Descartado por datos insuficientes", "es_version_servible": False, "exige_motivo": True, "orden": 3},
        ],
    )

    recurso_sistema = sa.table(
        "recurso_sistema",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("modulo", sa.String),
        sa.column("es_auditable", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        recurso_sistema,
        [
            {"codigo": "modelo_ml", "etiqueta": "Modelo de machine learning", "modulo": "011-analitica-reportes", "es_auditable": True, "orden": 23},
            {"codigo": "pipeline_etl", "etiqueta": "Pipeline ETL", "modulo": "011-analitica-reportes", "es_auditable": True, "orden": 24},
            {"codigo": "asistente", "etiqueta": "Asistente conversacional", "modulo": "011-analitica-reportes", "es_auditable": True, "orden": 25},
        ],
    )

    permiso_rol = sa.table(
        "permiso_rol",
        sa.column("rol", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("permitido", sa.Boolean),
    )

    # modelo_ml / pipeline_etl: dueño puede disparar reentrenos/corridas
    # (crear) además de consultar; el resto de roles con acceso a la
    # capa táctica (compras, sucursal) solo lectura; cajero sin acceso —
    # esto es analítica de dirección, no operación de POS.
    # asistente: RNF-AR-003 — exclusivo del rol dueño, validado además en
    # servicio (no expresable como CHECK, depende de usuario.rol).
    matrices = {
        "dueno": {
            "modelo_ml": {"crear": True, "leer": True, "actualizar": False},
            "pipeline_etl": {"crear": True, "leer": True, "actualizar": False},
            "asistente": {"crear": True, "leer": True, "actualizar": False},
        },
        "encargado_compras": {
            "modelo_ml": {"crear": False, "leer": True, "actualizar": False},
            "pipeline_etl": {"crear": False, "leer": True, "actualizar": False},
            "asistente": {"crear": False, "leer": False, "actualizar": False},
        },
        "encargado_sucursal": {
            "modelo_ml": {"crear": False, "leer": True, "actualizar": False},
            "pipeline_etl": {"crear": False, "leer": True, "actualizar": False},
            "asistente": {"crear": False, "leer": False, "actualizar": False},
        },
        "cajero": {
            "modelo_ml": {"crear": False, "leer": False, "actualizar": False},
            "pipeline_etl": {"crear": False, "leer": False, "actualizar": False},
            "asistente": {"crear": False, "leer": False, "actualizar": False},
        },
    }

    filas = [
        {"rol": rol_codigo, "recurso": recurso, "operacion": op_codigo, "permitido": permitido}
        for rol_codigo, matriz in matrices.items()
        for recurso, ops in matriz.items()
        for op_codigo, permitido in ops.items()
    ]
    op.bulk_insert(permiso_rol, filas)


def downgrade() -> None:
    op.execute("DELETE FROM permiso_rol WHERE recurso IN ('modelo_ml', 'pipeline_etl', 'asistente')")
    op.execute("DELETE FROM recurso_sistema WHERE codigo IN ('modelo_ml', 'pipeline_etl', 'asistente')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_segmento_cliente_version_modelo", "segmento_cliente", type_="foreignkey")
    op.drop_index('ix_validacion_calidad_ejecucion', table_name='validacion_calidad_datos')
    op.drop_table('validacion_calidad_datos')
    op.drop_index('ix_pregunta_asistente_usuario_fecha', table_name='pregunta_asistente')
    op.drop_table('pregunta_asistente')
    op.drop_index('ux_version_modelo_activa', table_name='version_modelo_ml', postgresql_where=sa.text("estado = 'activo'"))
    op.drop_table('version_modelo_ml')
    op.drop_index('ix_ejecucion_etl_fecha_inicio', table_name='ejecucion_pipeline_etl')
    op.drop_table('ejecucion_pipeline_etl')
    op.drop_table('modelo_ml')
    op.drop_table('estado_version_modelo')
    op.drop_table('estado_ejecucion')
    # ### end Alembic commands ###
