"""006_arqueo_parcial_turno

Cuadre de caja realmente horario — enmienda 2026-09-05, auditoría de
riesgos derivados. Decisión 5 de research.md (enmienda v1.1) ya explicó
por qué NO se impone un conteo físico obligatorio cada hora (carga
operativa + riesgo de volverse "simulado" si no se garantiza real cada
vez); esa decisión sigue vigente. Lo que faltaba era la POSIBILIDAD de un
conteo real, voluntario, a mitad de turno — hoy el cajero cuenta su
propia caja o el encargado de sucursal hace un spot-check de supervisión
sin previo aviso, algo que antes de esta migración no tenía dónde
registrarse: los checkpoints automáticos de `punto_control_horario_turno`
solo calculan el monto esperado, nunca comparan contra un conteo físico.

Revision ID: be425a3c0568
Revises: 38d12694f2c1
Create Date: 2026-09-05 20:01:01.392238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be425a3c0568'
down_revision: Union[str, None] = '38d12694f2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arqueo_parcial_turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_caja_id', sa.Integer(), nullable=False),
    sa.Column('monto_esperado_acumulado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_contado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('diferencia', sa.Numeric(precision=10, scale=2), sa.Computed('monto_contado - monto_esperado_acumulado', persisted=True), nullable=False),
    sa.Column('motivo_diferencia', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('hora_arqueo', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('diferencia = 0 OR motivo_diferencia IS NOT NULL', name='ck_arqueo_parcial_diferencia_requiere_motivo'),
    sa.CheckConstraint('monto_contado >= 0', name='ck_arqueo_parcial_monto_no_negativo'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['turno_caja_id'], ['turno_caja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_arqueo_parcial_turno_hora', 'arqueo_parcial_turno', ['turno_caja_id', 'hora_arqueo'], unique=False)
    # ### end Alembic commands ###
    _seed()


def _seed() -> None:
    recurso_sistema = sa.table(
        "recurso_sistema",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("modulo", sa.String),
        sa.column("es_auditable", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        recurso_sistema,
        [
            {"codigo": "arqueo_parcial", "etiqueta": "Arqueo parcial de turno", "modulo": "006-caja-mermas-fraude", "es_auditable": True, "orden": 21},
        ],
    )

    permiso_rol = sa.table(
        "permiso_rol",
        sa.column("rol", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("permitido", sa.Boolean),
    )

    # arqueo_parcial: recurso propio y separado de turno_caja a propósito —
    # ahí solo el cajero puede crear/actualizar (abre y cierra el suyo).
    # Acá tanto el cajero (cuenta su propia caja) como el encargado de
    # sucursal (spot-check de supervisión, mismo alcance que ya tiene sobre
    # merma/alerta_fraude) deben poder registrar uno. Compras solo lee.
    matrices = {
        "dueno": {"crear": True, "leer": True},
        "encargado_compras": {"crear": False, "leer": True},
        "encargado_sucursal": {"crear": True, "leer": True},
        "cajero": {"crear": True, "leer": True},
    }
    filas = [
        {"rol": rol_codigo, "recurso": "arqueo_parcial", "operacion": op_codigo, "permitido": permitido}
        for rol_codigo, ops in matrices.items()
        for op_codigo, permitido in ops.items()
    ]
    op.bulk_insert(permiso_rol, filas)


def downgrade() -> None:
    op.execute("DELETE FROM permiso_rol WHERE recurso = 'arqueo_parcial'")
    op.execute("DELETE FROM recurso_sistema WHERE codigo = 'arqueo_parcial'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_arqueo_parcial_turno_hora', table_name='arqueo_parcial_turno')
    op.drop_table('arqueo_parcial_turno')
    # ### end Alembic commands ###
