"""008_compras_proveedores

Revision ID: c1f8d70dba90
Revises: a17e3a247d84
Create Date: 2026-09-05 00:10:48.213251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f8d70dba90'
down_revision: Union[str, None] = 'a17e3a247d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_orden_compra',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('permite_recepcion', sa.Boolean(), nullable=False),
    sa.Column('es_estado_final', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('forma_pago',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('dias_plazo_default', sa.SmallInteger(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('dias_plazo_default >= 0', name='ck_forma_pago_plazo_no_negativo'),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('contacto', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orden_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('es_oferta', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('forma_pago', sa.String(length=40), server_default='contado', nullable=False),
    sa.Column('estado', sa.String(length=40), server_default='pendiente', nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['estado'], ['estado_orden_compra.codigo'], ),
    sa.ForeignKeyConstraint(['forma_pago'], ['forma_pago.codigo'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orden_compra_proveedor', 'orden_compra', ['proveedor_id'], unique=False)
    op.create_index('ix_orden_compra_sucursal_estado', 'orden_compra', ['sucursal_id', 'estado'], unique=False)
    op.create_table('detalle_orden_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_compra_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_pedida', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('precio_ofrecido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pronostico_consultado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cantidad_recomendada_pronostico', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('motivo_no_siguio_pronostico', sa.Text(), nullable=True),
    sa.CheckConstraint('cantidad_pedida > 0', name='ck_detalle_oc_cantidad_positiva'),
    sa.CheckConstraint('cantidad_recomendada_pronostico IS NULL OR cantidad_pedida <= cantidad_recomendada_pronostico OR motivo_no_siguio_pronostico IS NOT NULL', name='ck_detalle_oc_motivo_desvio_pronostico'),
    sa.CheckConstraint('precio_ofrecido >= 0', name='ck_detalle_oc_precio_no_negativo'),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['orden_compra.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detalle_oc_orden', 'detalle_orden_compra', ['orden_compra_id'], unique=False)
    op.create_index('ix_detalle_oc_producto', 'detalle_orden_compra', ['producto_id'], unique=False)
    op.create_table('historial_costo_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('orden_compra_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('costo >= 0', name='ck_historial_costo_no_negativo'),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['orden_compra.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_historial_costo_producto_proveedor_fecha', 'historial_costo_producto', ['producto_id', 'proveedor_id', 'fecha'], unique=False)
    op.create_table('recepcion_orden_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detalle_orden_compra_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_recibida_evento', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('numero_documento_proveedor', sa.Text(), nullable=True),
    sa.Column('fecha_recepcion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('cantidad_recibida_evento > 0', name='ck_recepcion_cantidad_positiva'),
    sa.ForeignKeyConstraint(['detalle_orden_compra_id'], ['detalle_orden_compra.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recepcion_detalle_fecha', 'recepcion_orden_compra', ['detalle_orden_compra_id', 'fecha_recepcion'], unique=False)
    # ### end Alembic commands ###

    _seed()


# ---------------------------------------------------------------------------
# Seed de los 2 catálogos de 008 (enmienda §7) + recursos/permisos RBAC.
# ---------------------------------------------------------------------------


def _seed() -> None:
    forma_pago = sa.table(
        "forma_pago",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("dias_plazo_default", sa.SmallInteger),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        forma_pago,
        [
            {"codigo": "contado", "etiqueta": "Contado", "dias_plazo_default": 0, "orden": 1},
            {"codigo": "credito", "etiqueta": "Crédito", "dias_plazo_default": 30, "orden": 2},
        ],
    )

    estado_orden_compra = sa.table(
        "estado_orden_compra",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("permite_recepcion", sa.Boolean),
        sa.column("es_estado_final", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        estado_orden_compra,
        [
            {"codigo": "pendiente", "etiqueta": "Pendiente", "permite_recepcion": True, "es_estado_final": False, "orden": 1},
            {"codigo": "recibida_parcial", "etiqueta": "Recibida parcial", "permite_recepcion": True, "es_estado_final": False, "orden": 2},
            {"codigo": "recibida_completa", "etiqueta": "Recibida completa", "permite_recepcion": False, "es_estado_final": True, "orden": 3},
            {"codigo": "cancelada", "etiqueta": "Cancelada", "permite_recepcion": False, "es_estado_final": True, "orden": 4},
        ],
    )

    recurso_sistema = sa.table(
        "recurso_sistema",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("modulo", sa.String),
        sa.column("es_auditable", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        recurso_sistema,
        [
            {"codigo": "proveedor", "etiqueta": "Proveedor", "modulo": "008-compras-proveedores", "es_auditable": True, "orden": 21},
            {"codigo": "orden_compra", "etiqueta": "Orden de compra y recepciones", "modulo": "008-compras-proveedores", "es_auditable": True, "orden": 22},
        ],
    )

    permiso_rol = sa.table(
        "permiso_rol",
        sa.column("rol", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("permitido", sa.Boolean),
    )

    # proveedor: dueño y compras lo administran (es literalmente el rol de
    # compras); sucursal solo consulta a quién le llega el pedido; cajero
    # sin acceso.
    # orden_compra (con su detalle, recepciones e historial de costo):
    # compras la crea y gestiona de punta a punta; dueño con control
    # total; sucursal registra recepciones en su local ("actualizar" del
    # progreso de la orden, nunca crea ni cancela); cajero sin acceso —
    # no es parte de su operación en el POS.
    matrices = {
        "dueno": {
            "proveedor": {"crear": True, "leer": True, "actualizar": True},
            "orden_compra": {"crear": True, "leer": True, "actualizar": True},
        },
        "encargado_compras": {
            "proveedor": {"crear": True, "leer": True, "actualizar": True},
            "orden_compra": {"crear": True, "leer": True, "actualizar": True},
        },
        "encargado_sucursal": {
            "proveedor": {"crear": False, "leer": True, "actualizar": False},
            "orden_compra": {"crear": False, "leer": True, "actualizar": True},
        },
        "cajero": {
            "proveedor": {"crear": False, "leer": False, "actualizar": False},
            "orden_compra": {"crear": False, "leer": False, "actualizar": False},
        },
    }

    filas = [
        {"rol": rol_codigo, "recurso": recurso, "operacion": op_codigo, "permitido": permitido}
        for rol_codigo, matriz in matrices.items()
        for recurso, ops in matriz.items()
        for op_codigo, permitido in ops.items()
    ]
    op.bulk_insert(permiso_rol, filas)


def downgrade() -> None:
    op.execute("DELETE FROM permiso_rol WHERE recurso IN ('proveedor', 'orden_compra')")
    op.execute("DELETE FROM recurso_sistema WHERE codigo IN ('proveedor', 'orden_compra')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recepcion_detalle_fecha', table_name='recepcion_orden_compra')
    op.drop_table('recepcion_orden_compra')
    op.drop_index('ix_historial_costo_producto_proveedor_fecha', table_name='historial_costo_producto')
    op.drop_table('historial_costo_producto')
    op.drop_index('ix_detalle_oc_producto', table_name='detalle_orden_compra')
    op.drop_index('ix_detalle_oc_orden', table_name='detalle_orden_compra')
    op.drop_table('detalle_orden_compra')
    op.drop_index('ix_orden_compra_sucursal_estado', table_name='orden_compra')
    op.drop_index('ix_orden_compra_proveedor', table_name='orden_compra')
    op.drop_table('orden_compra')
    op.drop_table('proveedor')
    op.drop_table('forma_pago')
    op.drop_table('estado_orden_compra')
    # ### end Alembic commands ###
