"""005_sugerencia_patron_compra

Enmienda v1.2 (auditoría de riesgos derivados, 2026-09-05). Cierra la
Decisión 3 de research.md: antes de esta migración, `tipo_origen =
'patron_compra'` (005) no tenía ningún proceso real detrás — se
documentaba como responsabilidad de "un proceso batch o la capa
estratégica" que en la práctica no existía, así que ese tipo de cupón solo
podía activarse a mano, sin ningún dato de soporte.

`sugerencia_patron_compra` es la salida de un cálculo real de asociación
de mercado (soporte/confianza/lift) sobre `detalle_venta`/`venta`
(`app/services/patron_compra.py`), nunca escrita a mano ni simulada.
Sigue "sistema sugiere, humano confirma" (mismo principio que
`recomendacion_precio`, RN-PM-002 de 003): esta tabla nunca crea un cupón
por sí sola, solo cuando `PATCH .../resolver` la acepta.

Revision ID: c267444e212d
Revises: be425a3c0568
Create Date: 2026-09-05 20:13:59.794953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c267444e212d'
down_revision: Union[str, None] = 'be425a3c0568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_sugerencia_patron',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('es_estado_final', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('sugerencia_patron_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('producto_base_id', sa.Integer(), nullable=False),
    sa.Column('producto_sugerido_id', sa.Integer(), nullable=False),
    sa.Column('veces_comprado_base', sa.Integer(), nullable=False),
    sa.Column('soporte', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('confianza', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('lift', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('periodo_dias', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=40), server_default='pendiente', nullable=False),
    sa.Column('generado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atendida_en', sa.DateTime(), nullable=True),
    sa.Column('atendida_por', sa.Integer(), nullable=True),
    sa.Column('cupon_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('confianza >= 0 AND confianza <= 1', name='ck_sugerencia_patron_confianza_rango'),
    sa.CheckConstraint('lift >= 0', name='ck_sugerencia_patron_lift_no_negativo'),
    sa.CheckConstraint('periodo_dias > 0', name='ck_sugerencia_patron_periodo_positivo'),
    sa.CheckConstraint('producto_base_id <> producto_sugerido_id', name='ck_sugerencia_patron_productos_distintos'),
    sa.CheckConstraint('soporte >= 0 AND soporte <= 1', name='ck_sugerencia_patron_soporte_rango'),
    sa.CheckConstraint('veces_comprado_base > 0', name='ck_sugerencia_patron_veces_positivo'),
    sa.ForeignKeyConstraint(['atendida_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['cupon_id'], ['cupon.id'], ),
    sa.ForeignKeyConstraint(['estado'], ['estado_sugerencia_patron.codigo'], ),
    sa.ForeignKeyConstraint(['producto_base_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['producto_sugerido_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sugerencia_patron_cliente_estado', 'sugerencia_patron_compra', ['cliente_id', 'estado'], unique=False)
    op.create_index('ux_sugerencia_patron_pendiente', 'sugerencia_patron_compra', ['cliente_id', 'producto_sugerido_id'], unique=True, postgresql_where=sa.text("estado = 'pendiente'"))
    # ### end Alembic commands ###
    _seed()


def _seed() -> None:
    estado_sugerencia_patron = sa.table(
        "estado_sugerencia_patron",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("es_estado_final", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        estado_sugerencia_patron,
        [
            {"codigo": "pendiente", "etiqueta": "Pendiente de revisión", "es_estado_final": False, "orden": 1},
            {"codigo": "aceptada", "etiqueta": "Aceptada (generó cupón)", "es_estado_final": True, "orden": 2},
            {"codigo": "descartada", "etiqueta": "Descartada", "es_estado_final": True, "orden": 3},
        ],
    )

    recurso_sistema = sa.table(
        "recurso_sistema",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("modulo", sa.String),
        sa.column("es_auditable", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        recurso_sistema,
        [
            {
                "codigo": "sugerencia_patron",
                "etiqueta": "Sugerencia de patrón de compra",
                "modulo": "005-promociones-inteligentes",
                "es_auditable": True,
                "orden": 16,
            },
        ],
    )

    permiso_rol = sa.table(
        "permiso_rol",
        sa.column("rol", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("permitido", sa.Boolean),
    )
    # Mismo criterio que "cupon" (ver docstring del router): crear
    # (recalcular el motor) y actualizar (aceptar/descartar, que compromete
    # presupuesto de descuento real) quedan dueño-exclusivo. Los cuatro
    # roles pueden leer las sugerencias generadas.
    matrices = {
        "dueno": {"crear": True, "leer": True, "actualizar": True},
        "encargado_compras": {"crear": False, "leer": True, "actualizar": False},
        "encargado_sucursal": {"crear": False, "leer": True, "actualizar": False},
        "cajero": {"crear": False, "leer": True, "actualizar": False},
    }
    filas = [
        {"rol": rol_codigo, "recurso": "sugerencia_patron", "operacion": op_codigo, "permitido": permitido}
        for rol_codigo, ops in matrices.items()
        for op_codigo, permitido in ops.items()
    ]
    op.bulk_insert(permiso_rol, filas)


def downgrade() -> None:
    op.execute("DELETE FROM permiso_rol WHERE recurso = 'sugerencia_patron'")
    op.execute("DELETE FROM recurso_sistema WHERE codigo = 'sugerencia_patron'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_sugerencia_patron_pendiente', table_name='sugerencia_patron_compra', postgresql_where=sa.text("estado = 'pendiente'"))
    op.drop_index('ix_sugerencia_patron_cliente_estado', table_name='sugerencia_patron_compra')
    op.drop_table('sugerencia_patron_compra')
    op.drop_table('estado_sugerencia_patron')
    # ### end Alembic commands ###
