"""002_clientes_fidelizacion

Revision ID: c3fd49d3797d
Revises: 39457fa875e2
Create Date: 2026-09-05 00:01:04.235961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3fd49d3797d'
down_revision: Union[str, None] = '39457fa875e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('contacto', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cliente_fecha_nacimiento', 'cliente', ['fecha_nacimiento'], unique=False)
    op.create_table('segmento',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('prioridad_comercial', sa.SmallInteger(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('prioridad_comercial BETWEEN 1 AND 10', name='ck_segmento_prioridad_rango'),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('evaluacion_churn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('es_riesgo_real', sa.Boolean(), nullable=False),
    sa.Column('dias_sin_compra_al_momento', sa.Integer(), nullable=False),
    sa.Column('frecuencia_historica_dias', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.Column('tamano_muestra', sa.Integer(), nullable=False),
    sa.Column('fecha_evaluacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dias_sin_compra_al_momento >= 0', name='ck_churn_dias_no_negativo'),
    sa.CheckConstraint('length(justificacion) >= 10', name='ck_churn_justificacion_minima'),
    sa.CheckConstraint('tamano_muestra > 0', name='ck_churn_muestra_positiva'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_churn_cliente_fecha', 'evaluacion_churn', ['cliente_id', 'fecha_evaluacion'], unique=False)
    op.create_table('segmento_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('segmento_codigo', sa.String(length=40), nullable=False),
    sa.Column('frecuencia_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('margen_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recencia_dias_snapshot', sa.Integer(), nullable=True),
    sa.Column('tamano_muestra', sa.Integer(), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fin', sa.Date(), nullable=False),
    sa.Column('version_modelo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('vigente_hasta', sa.DateTime(), nullable=True),
    sa.CheckConstraint('tamano_muestra > 0', name='ck_segmento_cliente_muestra_positiva'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['segmento_codigo'], ['segmento.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_segmento_cliente_cliente_fecha', 'segmento_cliente', ['cliente_id', 'fecha_calculo'], unique=False)
    op.create_index('ux_segmento_cliente_vigente', 'segmento_cliente', ['cliente_id'], unique=True, postgresql_where=sa.text('vigente_hasta IS NULL'))
    op.create_table('campana_recuperacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('evaluacion_churn_id', sa.Integer(), nullable=False),
    sa.Column('cupon_id', sa.Integer(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['evaluacion_churn_id'], ['evaluacion_churn.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Nombradas explícitamente (autogenerate las deja sin nombre) — cierran
    # las FKs diferidas de 010 y 001 ahora que `cliente` existe (ver
    # docstring de SolicitudArco y de core_ventas.py).
    op.create_foreign_key(
        "fk_solicitud_arco_cliente", "solicitud_arco", "cliente", ["cliente_id"], ["id"]
    )
    op.create_foreign_key("fk_venta_cliente", "venta", "cliente", ["cliente_id"], ["id"])
    # ### end Alembic commands ###

    _seed()


# ---------------------------------------------------------------------------
# Seed del catálogo `segmento` (enmienda §7) + recursos/permisos RBAC que
# este módulo agrega a la matriz de 010.
# ---------------------------------------------------------------------------


def _seed() -> None:
    segmento = sa.table(
        "segmento",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("descripcion", sa.Text),
        sa.column("prioridad_comercial", sa.SmallInteger),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        segmento,
        [
            {
                "codigo": "leal_alto_margen",
                "etiqueta": "Leal de alto margen",
                "descripcion": "Compra con frecuencia alta y margen por encima del promedio.",
                "prioridad_comercial": 9,
                "orden": 1,
            },
            {
                "codigo": "frecuente_bajo_margen",
                "etiqueta": "Frecuente de bajo margen",
                "descripcion": "Compra seguido pero en productos de margen bajo.",
                "prioridad_comercial": 6,
                "orden": 2,
            },
            {
                "codigo": "ocasional",
                "etiqueta": "Ocasional",
                "descripcion": "Frecuencia y margen dentro del promedio, sin patrón marcado.",
                "prioridad_comercial": 4,
                "orden": 3,
            },
            {
                "codigo": "nuevo",
                "etiqueta": "Nuevo",
                "descripcion": "Historial insuficiente todavía para caracterizar el comportamiento.",
                "prioridad_comercial": 5,
                "orden": 4,
            },
            {
                "codigo": "en_riesgo",
                "etiqueta": "En riesgo",
                "descripcion": "Recencia por encima de su frecuencia histórica — candidato a churn.",
                "prioridad_comercial": 10,
                "orden": 5,
            },
        ],
    )

    recurso_sistema = sa.table(
        "recurso_sistema",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("modulo", sa.String),
        sa.column("es_auditable", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        recurso_sistema,
        [
            {"codigo": "cliente", "etiqueta": "Cliente", "modulo": "002-clientes-fidelizacion", "es_auditable": True, "orden": 9},
            {"codigo": "churn", "etiqueta": "Evaluación de churn y campañas", "modulo": "002-clientes-fidelizacion", "es_auditable": True, "orden": 10},
        ],
    )

    permiso_rol = sa.table(
        "permiso_rol",
        sa.column("rol", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("permitido", sa.Boolean),
    )

    # cliente: dueño control total; sucursal registra/actualiza clientes en
    # el día a día; cajero puede registrar uno nuevo en el POS pero no
    # editarlo; compras solo consulta.
    # churn (evaluación + campaña de recuperación): decisión de negocio
    # sobre a quién recontactar — dueño con control total, el resto solo
    # lectura (la evaluación la produce el pipeline de 011, no una persona).
    matrices = {
        "dueno": {
            "cliente": {"crear": True, "leer": True, "actualizar": True},
            "churn": {"crear": True, "leer": True, "actualizar": True},
        },
        "encargado_compras": {
            "cliente": {"crear": False, "leer": True, "actualizar": False},
            "churn": {"crear": False, "leer": True, "actualizar": False},
        },
        "encargado_sucursal": {
            "cliente": {"crear": True, "leer": True, "actualizar": True},
            "churn": {"crear": False, "leer": True, "actualizar": False},
        },
        "cajero": {
            "cliente": {"crear": True, "leer": True, "actualizar": False},
            "churn": {"crear": False, "leer": False, "actualizar": False},
        },
    }

    filas = [
        {"rol": rol_codigo, "recurso": recurso, "operacion": op_codigo, "permitido": permitido}
        for rol_codigo, matriz in matrices.items()
        for recurso, ops in matriz.items()
        for op_codigo, permitido in ops.items()
    ]
    op.bulk_insert(permiso_rol, filas)


def downgrade() -> None:
    # Limpieza manual: filas de permiso_rol/recurso_sistema sembradas por
    # este módulo, en tablas de 010 que esta migración no dropea.
    op.execute("DELETE FROM permiso_rol WHERE recurso IN ('cliente', 'churn')")
    op.execute("DELETE FROM recurso_sistema WHERE codigo IN ('cliente', 'churn')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_venta_cliente", "venta", type_="foreignkey")
    op.drop_constraint("fk_solicitud_arco_cliente", "solicitud_arco", type_="foreignkey")
    op.drop_table('campana_recuperacion')
    op.drop_index('ux_segmento_cliente_vigente', table_name='segmento_cliente', postgresql_where=sa.text('vigente_hasta IS NULL'))
    op.drop_index('ix_segmento_cliente_cliente_fecha', table_name='segmento_cliente')
    op.drop_table('segmento_cliente')
    op.drop_index('ix_churn_cliente_fecha', table_name='evaluacion_churn')
    op.drop_table('evaluacion_churn')
    op.drop_table('segmento')
    op.drop_index('ix_cliente_fecha_nacimiento', table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
