"""006_caja_mermas_fraude

Revision ID: d2561626e432
Revises: 82c345f5dec1
Create Date: 2026-09-05 00:08:13.878341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2561626e432'
down_revision: Union[str, None] = '82c345f5dec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('causa_merma',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('es_atribuible_a_persona', sa.Boolean(), nullable=False),
    sa.Column('requiere_investigacion', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('estado_alerta',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('es_estado_final', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('estado_incidencia',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('es_estado_final', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('estado_turno',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('es_estado_final', sa.Boolean(), nullable=False),
    sa.Column('admite_ventas', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('resultado_investigacion',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('cierra_investigacion', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('merma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('valor_estimado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('causa', sa.String(length=40), nullable=True),
    sa.Column('resultado_investigacion', sa.String(length=40), nullable=True),
    sa.Column('fecha_deteccion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_resultado', sa.DateTime(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('investigado_por', sa.Integer(), nullable=True),
    sa.CheckConstraint('cantidad > 0', name='ck_merma_cantidad_positiva'),
    sa.CheckConstraint('resultado_investigacion IS NULL OR causa IS NOT NULL', name='ck_merma_resultado_requiere_causa'),
    sa.CheckConstraint('valor_estimado > 0', name='ck_merma_valor_positivo'),
    sa.ForeignKeyConstraint(['causa'], ['causa_merma.codigo'], ),
    sa.ForeignKeyConstraint(['investigado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['resultado_investigacion'], ['resultado_investigacion.codigo'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_merma_sucursal_causa_fecha', 'merma', ['sucursal_id', 'causa', 'fecha_deteccion'], unique=False)
    op.create_table('turno_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('cajero_id', sa.Integer(), nullable=False),
    sa.Column('hora_apertura', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('monto_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hora_cierre', sa.DateTime(), nullable=True),
    sa.Column('monto_contado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_esperado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diferencia', sa.Numeric(precision=10, scale=2), sa.Computed('monto_contado - monto_esperado', persisted=True), nullable=True),
    sa.Column('motivo_diferencia', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=40), server_default='abierto', nullable=False),
    sa.CheckConstraint("estado <> 'cerrado' OR diferencia = 0 OR motivo_diferencia IS NOT NULL", name='ck_turno_diferencia_requiere_motivo'),
    sa.CheckConstraint('monto_contado IS NULL OR monto_contado >= 0', name='ck_turno_monto_contado_no_negativo'),
    sa.CheckConstraint('monto_inicial >= 0', name='ck_turno_monto_inicial_no_negativo'),
    sa.ForeignKeyConstraint(['cajero_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['estado'], ['estado_turno.codigo'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_turno_sucursal_estado', 'turno_caja', ['sucursal_id', 'estado'], unique=False)
    op.create_index('ux_turno_cajero_abierto', 'turno_caja', ['cajero_id'], unique=True, postgresql_where=sa.text("estado = 'abierto'"))
    op.create_table('incidencia_cuadre_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_caja_id', sa.Integer(), nullable=False),
    sa.Column('score_anomalia', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=40), server_default='pendiente', nullable=False),
    sa.Column('fecha_deteccion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atendida_por', sa.Integer(), nullable=True),
    sa.Column('fecha_atencion', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(justificacion) >= 10', name='ck_incidencia_justificacion_minima'),
    sa.ForeignKeyConstraint(['atendida_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['estado'], ['estado_incidencia.codigo'], ),
    sa.ForeignKeyConstraint(['turno_caja_id'], ['turno_caja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidencia_estado', 'incidencia_cuadre_caja', ['estado'], unique=False)
    op.create_index('ux_incidencia_turno_pendiente', 'incidencia_cuadre_caja', ['turno_caja_id'], unique=True, postgresql_where=sa.text("estado = 'pendiente'"))
    op.create_table('punto_control_horario_turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_caja_id', sa.Integer(), nullable=False),
    sa.Column('hora_checkpoint', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('monto_esperado_acumulado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('generado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monto_esperado_acumulado >= 0', name='ck_punto_control_monto_no_negativo'),
    sa.ForeignKeyConstraint(['turno_caja_id'], ['turno_caja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_punto_control_turno_hora', 'punto_control_horario_turno', ['turno_caja_id', 'hora_checkpoint'], unique=False)
    op.create_table('alerta_fraude_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=40), server_default='abierta', nullable=False),
    sa.Column('ultimos_4_digitos', sa.CHAR(length=4), nullable=True),
    sa.Column('codigo_respuesta_proveedor', sa.Text(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atendida_en', sa.DateTime(), nullable=True),
    sa.Column('atendida_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atendida_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['estado'], ['estado_alerta.codigo'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerta_fraude_estado', 'alerta_fraude_pago', ['estado'], unique=False)
    op.create_index('ix_alerta_fraude_venta', 'alerta_fraude_pago', ['venta_id'], unique=False)
    # Cierra la última FK diferida de 001 (nombrada a mano).
    op.create_foreign_key("fk_venta_turno_caja", "venta", "turno_caja", ["turno_caja_id"], ["id"])
    # ### end Alembic commands ###

    _seed()


# ---------------------------------------------------------------------------
# Seed de los 5 catálogos de 006 (enmienda §7) + recursos/permisos RBAC.
# ---------------------------------------------------------------------------


def _seed() -> None:
    causa_merma = sa.table(
        "causa_merma",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("es_atribuible_a_persona", sa.Boolean),
        sa.column("requiere_investigacion", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        causa_merma,
        [
            {"codigo": "robo_externo", "etiqueta": "Robo externo", "es_atribuible_a_persona": False, "requiere_investigacion": True, "orden": 1},
            {"codigo": "error_humano", "etiqueta": "Error humano", "es_atribuible_a_persona": True, "requiere_investigacion": True, "orden": 2},
            {"codigo": "fraude_interno", "etiqueta": "Fraude interno", "es_atribuible_a_persona": True, "requiere_investigacion": True, "orden": 3},
            {"codigo": "caducidad", "etiqueta": "Caducidad", "es_atribuible_a_persona": False, "requiere_investigacion": False, "orden": 4},
        ],
    )

    resultado_investigacion = sa.table(
        "resultado_investigacion",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("cierra_investigacion", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        resultado_investigacion,
        [
            {"codigo": "confirmada", "etiqueta": "Confirmada", "cierra_investigacion": True, "orden": 1},
            {"codigo": "descartada", "etiqueta": "Descartada", "cierra_investigacion": True, "orden": 2},
        ],
    )

    estado_turno = sa.table(
        "estado_turno",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("es_estado_final", sa.Boolean),
        sa.column("admite_ventas", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        estado_turno,
        [
            {"codigo": "abierto", "etiqueta": "Abierto", "es_estado_final": False, "admite_ventas": True, "orden": 1},
            {"codigo": "cerrado", "etiqueta": "Cerrado", "es_estado_final": True, "admite_ventas": False, "orden": 2},
        ],
    )

    estado_alerta = sa.table(
        "estado_alerta",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("es_estado_final", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        estado_alerta,
        [
            {"codigo": "abierta", "etiqueta": "Abierta", "es_estado_final": False, "orden": 1},
            {"codigo": "atendida", "etiqueta": "Atendida", "es_estado_final": True, "orden": 2},
        ],
    )

    estado_incidencia = sa.table(
        "estado_incidencia",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("es_estado_final", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        estado_incidencia,
        [
            {"codigo": "pendiente", "etiqueta": "Pendiente", "es_estado_final": False, "orden": 1},
            {"codigo": "atendida", "etiqueta": "Atendida", "es_estado_final": True, "orden": 2},
        ],
    )

    recurso_sistema = sa.table(
        "recurso_sistema",
        sa.column("codigo", sa.String),
        sa.column("etiqueta", sa.String),
        sa.column("modulo", sa.String),
        sa.column("es_auditable", sa.Boolean),
        sa.column("orden", sa.SmallInteger),
    )
    op.bulk_insert(
        recurso_sistema,
        [
            {"codigo": "turno_caja", "etiqueta": "Turno de caja", "modulo": "006-caja-mermas-fraude", "es_auditable": True, "orden": 16},
            {"codigo": "alerta_fraude", "etiqueta": "Alerta de fraude en pago", "modulo": "006-caja-mermas-fraude", "es_auditable": True, "orden": 17},
            {"codigo": "merma", "etiqueta": "Merma", "modulo": "006-caja-mermas-fraude", "es_auditable": True, "orden": 18},
            {"codigo": "incidencia_cuadre", "etiqueta": "Incidencia de cuadre de caja", "modulo": "006-caja-mermas-fraude", "es_auditable": True, "orden": 19},
        ],
    )

    permiso_rol = sa.table(
        "permiso_rol",
        sa.column("rol", sa.String),
        sa.column("recurso", sa.String),
        sa.column("operacion", sa.String),
        sa.column("permitido", sa.Boolean),
    )

    # turno_caja: el cajero abre/cierra el suyo (crear=abrir, actualizar=
    # cerrar); sucursal lo supervisa; dueño y compras solo consultan.
    # alerta_fraude: solo el UPDATE de atención es de este módulo (el
    # INSERT lo hace 001) — dueño y sucursal pueden atenderla, cajero no
    # (conflicto de interés: es sobre su propia venta), compras solo lee.
    # merma: dueño y sucursal la registran/investigan; cajero solo la
    # reporta (crear), no resuelve la investigación; compras solo lee.
    # incidencia_cuadre: generada por el modelo, nunca por POST humano —
    # "crear" queda en false para todos los roles; solo se actualiza
    # (atender) por dueño y sucursal.
    matrices = {
        "dueno": {
            "turno_caja": {"crear": False, "leer": True, "actualizar": False},
            "alerta_fraude": {"crear": False, "leer": True, "actualizar": True},
            "merma": {"crear": True, "leer": True, "actualizar": True},
            "incidencia_cuadre": {"crear": False, "leer": True, "actualizar": True},
        },
        "encargado_compras": {
            "turno_caja": {"crear": False, "leer": True, "actualizar": False},
            "alerta_fraude": {"crear": False, "leer": True, "actualizar": False},
            "merma": {"crear": False, "leer": True, "actualizar": False},
            "incidencia_cuadre": {"crear": False, "leer": True, "actualizar": False},
        },
        "encargado_sucursal": {
            "turno_caja": {"crear": False, "leer": True, "actualizar": False},
            "alerta_fraude": {"crear": False, "leer": True, "actualizar": True},
            "merma": {"crear": True, "leer": True, "actualizar": True},
            "incidencia_cuadre": {"crear": False, "leer": True, "actualizar": True},
        },
        "cajero": {
            "turno_caja": {"crear": True, "leer": True, "actualizar": True},
            "alerta_fraude": {"crear": False, "leer": False, "actualizar": False},
            "merma": {"crear": True, "leer": True, "actualizar": False},
            "incidencia_cuadre": {"crear": False, "leer": False, "actualizar": False},
        },
    }

    filas = [
        {"rol": rol_codigo, "recurso": recurso, "operacion": op_codigo, "permitido": permitido}
        for rol_codigo, matriz in matrices.items()
        for recurso, ops in matriz.items()
        for op_codigo, permitido in ops.items()
    ]
    op.bulk_insert(permiso_rol, filas)


def downgrade() -> None:
    op.execute(
        "DELETE FROM permiso_rol WHERE recurso IN "
        "('turno_caja', 'alerta_fraude', 'merma', 'incidencia_cuadre')"
    )
    op.execute(
        "DELETE FROM recurso_sistema WHERE codigo IN "
        "('turno_caja', 'alerta_fraude', 'merma', 'incidencia_cuadre')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_venta_turno_caja", "venta", type_="foreignkey")
    op.drop_index('ix_alerta_fraude_venta', table_name='alerta_fraude_pago')
    op.drop_index('ix_alerta_fraude_estado', table_name='alerta_fraude_pago')
    op.drop_table('alerta_fraude_pago')
    op.drop_index('ix_punto_control_turno_hora', table_name='punto_control_horario_turno')
    op.drop_table('punto_control_horario_turno')
    op.drop_index('ux_incidencia_turno_pendiente', table_name='incidencia_cuadre_caja', postgresql_where=sa.text("estado = 'pendiente'"))
    op.drop_index('ix_incidencia_estado', table_name='incidencia_cuadre_caja')
    op.drop_table('incidencia_cuadre_caja')
    op.drop_index('ux_turno_cajero_abierto', table_name='turno_caja', postgresql_where=sa.text("estado = 'abierto'"))
    op.drop_index('ix_turno_sucursal_estado', table_name='turno_caja')
    op.drop_table('turno_caja')
    op.drop_index('ix_merma_sucursal_causa_fecha', table_name='merma')
    op.drop_table('merma')
    op.drop_table('resultado_investigacion')
    op.drop_table('estado_turno')
    op.drop_table('estado_incidencia')
    op.drop_table('estado_alerta')
    op.drop_table('causa_merma')
    # ### end Alembic commands ###
